'use strict';

const CODE_BACK_SLASH = 92;
const CODE_FORWARD_SLASH = 47;
const CODE_OPEN_ANGLE_BRACKET = 60;
const CODE_CLOSE_ANGLE_BRACKET = 62;
const CODE_EXCLAMATION = 33;
const CODE_QUESTION = 63;
const CODE_OPEN_SQUARE_BRACKET = 91;
const CODE_CLOSE_SQUARE_BRACKET = 93;
const CODE_EQUAL = 61;
const CODE_SINGLE_QUOTE = 39;
const CODE_DOUBLE_QUOTE = 34;
const CODE_BACKTICK = 96;
const CODE_OPEN_PAREN = 40;
const CODE_CLOSE_PAREN = 41;
const CODE_OPEN_CURLY_BRACE = 123;
const CODE_CLOSE_CURLY_BRACE = 125;
const CODE_ASTERISK = 42;
const CODE_HYPHEN = 45;
const CODE_DOLLAR = 36;
const CODE_PERCENT = 37;
const CODE_PERIOD = 46;
const CODE_COMMA = 44;
const CODE_COLON = 58;
const CODE_SEMICOLON = 59;
const CODE_NUMBER_SIGN = 35;
const CODE_PIPE = 124;

module.exports = {
    CODE_BACK_SLASH,
    CODE_FORWARD_SLASH,
    CODE_OPEN_ANGLE_BRACKET,
    CODE_CLOSE_ANGLE_BRACKET,
    CODE_EXCLAMATION,
    CODE_QUESTION,
    CODE_OPEN_SQUARE_BRACKET,
    CODE_CLOSE_SQUARE_BRACKET,
    CODE_EQUAL,
    CODE_SINGLE_QUOTE,
    CODE_DOUBLE_QUOTE,
    CODE_BACKTICK,
    CODE_OPEN_PAREN,
    CODE_CLOSE_PAREN,
    CODE_OPEN_CURLY_BRACE,
    CODE_CLOSE_CURLY_BRACE,
    CODE_ASTERISK,
    CODE_HYPHEN,
    CODE_HTML_BLOCK_DELIMITER: CODE_HYPHEN,
    CODE_DOLLAR,
    CODE_PERCENT,
    CODE_PERIOD,
    CODE_COMMA,
    CODE_COLON,
    CODE_SEMICOLON,
    CODE_NUMBER_SIGN,
    CODE_PIPE,
};
