// Deterministic A/B throughput runner — no mitata, minimal overhead. Ideal for
// quick iteration and for profiling (e.g. `node --cpu-prof bench/run.ts`).
//
// When a baseline is available it INTERLEAVES current/baseline samples so that
// CPU frequency drift and ordering effects cancel out — this is what makes
// sub-1% deltas detectable on noisy (cloud) CPUs.
//
// Usage:
//   node bench/run.ts                 # measure current source
//   ITERS=400 node bench/run.ts       # control sample count
//   BASELINE=... node bench/run.ts    # also measure baseline and report delta
//   GREP=examples node bench/run.ts   # restrict the corpus
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { corpusStats, loadCorpus } from "./corpus.ts";
import { type BenchSink, createHandlers, newSink } from "./handlers.ts";
import { loadBaseline, loadCurrent, type ParserAPI } from "./parser.ts";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ITERS = Number(process.env.ITERS || 200);
const WARMUP = Number(process.env.WARMUP || 30);
const files = loadCorpus();
const stats = corpusStats(files);

// A single large, error-free input (generated by collect.ts) isolates
// steady-state parsing throughput from the fixed per-parse overhead that
// dominates the many tiny fixture files.
const concat = fs.readFileSync(path.join(HERE, "steady-state.marko"), "utf-8");

interface Target {
  parse: () => void;
  sink: BenchSink;
}

function makeTarget(api: ParserAPI, src?: string): Target {
  const sink = newSink();
  const parser = api.createParser(createHandlers(sink));
  if (src === undefined) {
    return {
      sink,
      parse() {
        for (const f of files) {
          sink.src = f.src;
          parser.parse(f.src);
        }
      },
    };
  }
  return {
    sink,
    parse() {
      sink.src = src;
      parser.parse(src);
    },
  };
}

function time(parse: () => void) {
  const t = performance.now();
  parse();
  return performance.now() - t;
}

function median(xs: number[]) {
  const s = [...xs].sort((a, b) => a - b);
  return s[s.length >> 1];
}

/** Interleaved A/B sampling so drift cancels; returns best & median per side. */
function compare(a: Target, b?: Target) {
  for (let i = 0; i < WARMUP; i++) {
    a.parse();
    b?.parse();
  }
  (globalThis as { gc?: () => void }).gc?.();

  const aT: number[] = [];
  const bT: number[] = [];
  for (let i = 0; i < ITERS; i++) {
    aT.push(time(a.parse));
    if (b) bT.push(time(b.parse));
  }
  return { a: aT, b: bT };
}

function report(label: string, bytes: number, a: Target, b?: Target) {
  const { a: aT, b: bT } = compare(a, b);
  const mbps = (t: number) => (bytes / 1e6 / (t / 1000)).toFixed(1);
  const line = (name: string, ts: number[]) =>
    `  ${name.padEnd(9)} best=${Math.min(...ts).toFixed(3)}ms median=${median(
      ts,
    ).toFixed(3)}ms  ${mbps(Math.min(...ts))} MB/s`;

  console.log(`[${label}] ${(bytes / 1024).toFixed(1)} KiB/pass`);
  console.log(line("current", aT));
  if (b) {
    console.log(line("baseline", bT));
    const delta = ((Math.min(...bT) - Math.min(...aT)) / Math.min(...bT)) * 100;
    const dMed = ((median(bT) - median(aT)) / median(bT)) * 100;
    console.log(
      `  Δ best ${delta >= 0 ? "+" : ""}${delta.toFixed(2)}%, ` +
        `median ${dMed >= 0 ? "+" : ""}${dMed.toFixed(2)}% (positive = current faster)`,
    );
    if (a.sink.sum !== b.sink.sum) {
      console.error(
        `  ⚠️  checksum mismatch (current=${a.sink.sum}, baseline=${b.sink.sum}) — output changed!`,
      );
      process.exitCode = 1;
    }
  }
  console.log();
}

const current = await loadCurrent();
const baseline = await loadBaseline();

console.log(
  `corpus: ${stats.count} files, ${(stats.bytes / 1024).toFixed(
    1,
  )} KiB; iters=${ITERS} warmup=${WARMUP}${
    baseline ? " (interleaved A/B)" : ""
  }\n`,
);

report(
  "per-file corpus",
  stats.bytes,
  makeTarget(current),
  baseline && makeTarget(baseline),
);
report(
  "concat (steady-state)",
  Buffer.byteLength(concat),
  makeTarget(current, concat),
  baseline && makeTarget(baseline, concat),
);
